import {
  Bot,
  BookOpenText,
  Home,
  MessageSquare,
  RadioTower,
  Settings,
  ServerCog,
  Sparkles,
  SquareActivity,
  Workflow,
  GitBranch,
  FileJson,
  Gauge,
  MonitorUp,
  Users,
  type LucideIcon,
} from 'lucide-react';
import { K } from '@/i18n/keys';

export interface NavigationItem {
  to: string;
  label: string;
  title: string;
  description: string;
  labelKey: string;
  titleKey: string;
  descriptionKey: string;
  icon: LucideIcon;
  end?: boolean;
  requireRole?: 'viewer' | 'operator' | 'admin' | 'owner';
}

export const navigationItems: NavigationItem[] = [
  {
    to: '/',
    label: '首页',
    title: '首页',
    description: 'Haro Web 控制台入口。',
    labelKey: K.NAV.HOME,
    titleKey: K.NAV.HOME,
    descriptionKey: K.NAV.HOME_DESC,
    icon: Home,
    end: true,
  },
  {
    to: '/chat',
    label: '对话',
    title: '对话',
    description: '与 Agent 对话并实时查看事件流。',
    labelKey: K.NAV.CHAT,
    titleKey: K.NAV.CHAT,
    descriptionKey: K.NAV.CHAT_DESC,
    icon: MessageSquare,
  },
  {
    to: '/dispatch',
    label: '编排',
    title: '编排',
    description: '查看 workflow 拓扑、checkpoint timeline 与 stalled branch。',
    labelKey: K.NAV.DISPATCH,
    titleKey: K.NAV.DISPATCH,
    descriptionKey: K.NAV.DISPATCH_DESC,
    icon: GitBranch,
  },
  {
    to: '/knowledge',
    label: '知识',
    title: '知识',
    description: '搜索、浏览和安全写入 Memory Fabric 知识。',
    labelKey: K.NAV.KNOWLEDGE,
    titleKey: K.NAV.KNOWLEDGE,
    descriptionKey: K.NAV.KNOWLEDGE_DESC,
    icon: BookOpenText,
  },
  {
    to: '/skills',
    label: '技能',
    title: '技能',
    description: '管理预装和用户技能，并查看资产审计状态。',
    labelKey: K.NAV.SKILLS,
    titleKey: K.NAV.SKILLS,
    descriptionKey: K.NAV.SKILLS_DESC,
    icon: Sparkles,
  },
  {
    to: '/logs',
    label: '日志',
    title: '日志',
    description: '查询 session events、结构化 JSON 与 provider fallback log。',
    labelKey: K.NAV.LOGS,
    titleKey: K.NAV.LOGS,
    descriptionKey: K.NAV.LOGS_DESC,
    icon: FileJson,
  },
  {
    to: '/invoke',
    label: '调用',
    title: '调用',
    description: '查看 provider/model 调用统计、延迟与 token 趋势。',
    labelKey: K.NAV.INVOKE,
    titleKey: K.NAV.INVOKE,
    descriptionKey: K.NAV.INVOKE_DESC,
    icon: Gauge,
  },
  {
    to: '/monitor',
    label: '监控',
    title: '监控',
    description: '实时查看 system.status、session.update 与 provider 告警。',
    labelKey: K.NAV.MONITOR,
    titleKey: K.NAV.MONITOR,
    descriptionKey: K.NAV.MONITOR_DESC,
    icon: MonitorUp,
  },
  {
    to: '/sessions',
    label: '会话',
    title: '会话',
    description: '分页浏览 Agent sessions 与事件历史。',
    labelKey: K.NAV.SESSIONS,
    titleKey: K.NAV.SESSIONS,
    descriptionKey: K.NAV.SESSIONS_DESC,
    icon: Workflow,
  },
  {
    to: '/status',
    label: '状态',
    title: '状态',
    description: '系统健康、doctor 报告与 channel 只读摘要。',
    labelKey: K.NAV.STATUS,
    titleKey: K.NAV.STATUS,
    descriptionKey: K.NAV.STATUS_DESC,
    icon: SquareActivity,
  },
  {
    to: '/channels',
    label: '通道',
    title: '通道',
    description: 'Channel 启停、删除、Setup 与 Doctor。',
    labelKey: K.NAV.CHANNELS,
    titleKey: K.NAV.CHANNELS,
    descriptionKey: K.NAV.CHANNELS_DESC,
    icon: RadioTower,
  },
  {
    to: '/gateway',
    label: '网关',
    title: '网关',
    description: 'Gateway 状态、Start/Stop、Doctor 与日志。',
    labelKey: K.NAV.GATEWAY,
    titleKey: K.NAV.GATEWAY,
    descriptionKey: K.NAV.GATEWAY_DESC,
    icon: ServerCog,
  },
  {
    to: '/agents',
    label: 'Agent',
    title: 'Agent',
    description: 'Agent YAML 创建、编辑、校验与删除。',
    labelKey: K.NAV.AGENTS,
    titleKey: K.NAV.AGENTS,
    descriptionKey: K.NAV.AGENTS_DESC,
    icon: Bot,
  },
  {
    to: '/users',
    label: '用户',
    title: '用户',
    description: '本地 Web 用户、角色和审计摘要。',
    labelKey: K.NAV.USERS,
    titleKey: K.NAV.USERS,
    descriptionKey: K.NAV.USERS_DESC,
    icon: Users,
    requireRole: 'admin',
  },
  {
    to: '/settings',
    label: '设置',
    title: '设置',
    description: '项目级配置查看、校验与保存。',
    labelKey: K.NAV.SETTINGS,
    titleKey: K.NAV.SETTINGS,
    descriptionKey: K.NAV.SETTINGS_DESC,
    icon: Settings,
  },
];

export const fallbackPageMeta = {
  title: '控制台',
  description: '当前页面尚未配置标题映射。',
  titleKey: K.COMMON.DASHBOARD,
  descriptionKey: K.NAV.FALLBACK_DESC,
};
